services:
  # Backend API service
  - type: web
    name: horizon-blog-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000

  # Frontend service
  - type: web
    name: horizon-blog-client
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://horizon-blog-api.onrender.com 